cargo-features = ["edition2024"]

[package]
name = "simple_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
# You can add your dependencies here if needed.


[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/main.rs"

